### ISSUE TITLE
Can't augment data on Windows 10 - WSL 2 - Ubuntu 20.04

### ISSUE THREAD

**Issue by larrouvignod** [lootag/ImageAuGomentationCLI#1]
Description of the issue: can't augment pictures with annotations 
System: Windows 10, WSL 2 - Ubuntu 20.04, Go language up to date

Error: 
louis@G3:/Deeplearning/Downloads$ augoment -batch_size=50
panic: open ./Annotations/adidas_450.jxml: no such file or directory

goroutine 7 [running]:
github.com/lootag/ImageAuGomentationCLI/annotationReaders.PascalVocReader.ReadSync(0xc000116000, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Image/annotationReaders/PascalVocReader.go:51 +0x471
github.com/lootag/ImageAuGomentationCLI/exclusion.readAnnotations(0x0, 0xc000012730, 0xc0000642a0, 0xc000064300)
        /Image/exclusion/ExclusionService.go:74 +0x102
created by github.com/lootag/ImageAuGomentationCLI/exclusion.ExclusionService.GetClassesToExclude
        /Image/exclusion/ExclusionService.go:38 +0x150

**Comment by lootag** [comment]
Dear user,
the problem does not lie with WSL. 
You probably have some image which ends in .jpeg instead of .jpg. Rename it and it'll be okay 😃

**Comment by lootag** [comment]
Dear user, 
I'm closing the issue since the tool's latest release supports all image formats. Just watch out not to input files that have an extension which contains a number (e.g. jp2).
Let me know if you run into other problems :-)
