### ISSUE TITLE
panic: open ./Annotations/.DS_Stxml: no such file or directory

### ISSUE THREAD

**Issue by ZiningJin** [lootag/ImageAuGomentationCLI#3]
(base) charliejin@CharlieJins-MacBook-Air UA % augoment -batch_size=50 -blur=3
panic: open ./Annotations/.DS_Stxml: no such file or directory

goroutine 5 [running]:
github.com/lootag/ImageAuGomentationCLI/annotationReaders.PascalVocReader.ReadSync(0xc000200020, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/charliejin/ImageAuGomentationCLI/annotationReaders/PascalVocReader.go:51 +0x46d
github.com/lootag/ImageAuGomentationCLI/exclusion.readAnnotations(0x0, 0xc0000190a0, 0xc000070240, 0xc0000702a0)
	/Users/charliejin/ImageAuGomentationCLI/exclusion/ExclusionService.go:74 +0xf9
created by github.com/lootag/ImageAuGomentationCLI/exclusion.ExclusionService.GetClassesToExclude
	/Users/charliejin/ImageAuGomentationCLI/exclusion/ExclusionService.go:38 +0x150

**Comment by lootag** [comment]
Please check out issue #2 😃 I'll close this now!
