### ISSUE TITLE
Panic: augoment requires at most 6 arguments (Ubuntu 20, WSL)

### ISSUE THREAD

**Issue by guglielmogattiglio** [lootag/ImageAuGomentationCLI#4]
![image](https://user-images.githubusercontent.com/32592364/98465502-b4c6c280-21c9-11eb-8dfb-eef543388598.png)

I think the image explains itself. Just note how I passed fewer than 6 arguments. Finally, according to -h, I may pass up to 11 arguments, so I think that error message should be updated anyway (and the logic behind it).

Thank you.

**Comment by lootag** [comment]
Hey Guglielmo,
I solved the issue: I've updated the number of command line arguments that the program can take.
However, I'd like to point out that you're misusing the cli. You need to set the arguments using "=". 
In your case you'd have to run: ImageAuGomentationCLI -exclusion_threshold=1 -folder=/mnt/d/temp -rotate=skip -batch_size=1.
However I'm curious: why are you setting the batch size to one?

**Comment by guglielmogattiglio** [comment]
Hi, thank you for getting back to me. I was testing the repo with 3 images so I had to set a small batch size.

Thanks
