### ISSUE TITLE
Panic: open ./Annotations/3.xml: no such file or directory

### ISSUE THREAD

**Issue by guglielmogattiglio** [lootag/ImageAuGomentationCLI#5]
![image](https://user-images.githubusercontent.com/32592364/98471387-1bf56e80-21ec-11eb-92dc-2806a9c6a833.png)

Seems to me like -folder is applied only to ../Images but not to ../Annotations. In fact, in ../Images I have:
1.jpg
2.jpg
3.jpg

If I run it locally without -folder, it works fine.

Thank you

**Comment by lootag** [comment]
You're right, I'll fix that and make a new release 😃 
Thanks for reporting the bugs so thouroughly!

**Comment by lootag** [comment]
This is fixed now, try it out and close it if it works :-)
