### ISSUE TITLE
Augmented xml contains lowercase label for bounding box

### ISSUE THREAD

**Issue by guglielmogattiglio** [lootag/ImageAuGomentationCLI#6]
Just as the title says, input xml looks like 

```
<object>
		<name>Flag</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>3952</xmin>
			<ymin>1961</ymin>
			<xmax>4255</xmax>
			<ymax>2290</ymax>
		</bndbox>
	</object>
```
Then I process it and I get 
```
<object>
		<name>flag</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>277</xmin>
			<ymin>237</ymin>
			<xmax>298</xmax>
			<ymax>277</ymax>
		</bndbox>
	</object>
```
I am running
```
~/my_files/cv_proj/ImageAuGomentationCLI/ImageAuGomentationCLI -exclusion_threshold=1 -folder="/mnt/d/temp" -rotate='skip' -batch_size=1 -blur=0
```
Finally, I attached a zip containing a reproducible example (with the results I get running it)
[issue_example.zip](https://github.com/lootag/ImageAuGomentationCLI/files/5506810/issue_example.zip)

Thank you

**Comment by lootag** [comment]
That's actually right, I did it on purpouse, so that you don't have to worry about inconsistencies in the casing of the annotations.

**Comment by guglielmogattiglio** [comment]
Ok, I guess it's good practice anyway to keep everything lowercase. Thanks
