### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by guglielmogattiglio** [lootag/ImageAuGomentationCLI#7]
Sorry I am opening yet another issue. This time I am not sure what is going on, and although the error is reproducible (I set a seed) is not immediate for me to create a small sample where the error occurs. Any idea what could cause this? I am sure it's always the same image/xml pair, as running with batch_size=1 I get

![image](https://user-images.githubusercontent.com/32592364/98487713-eae56000-2224-11eb-9eb6-95008ada361e.png)

Before executing augoment I converted all *.png, *.jpeg, *.PNG to .jpg according to 

```
def convert_to_jpg(path):
    dir, file = os.path.split(path) 
    img_name,_ = os.path.splitext(file)
    img = PIL.Image.open(path)
    img = img.convert('RGB')
    img.save(join_path(dir, img_name + '.jpg'))
    img.close()
```
Thanks for the support.

**Comment by lootag** [comment]
If you're sure it's the same image/xml pair just send it to me for evaluation. Thanks :-)

**Comment by guglielmogattiglio** [comment]
I don't know which one though, it doesn't provide info about which image is processing.

**Comment by guglielmogattiglio** [comment]
Following up to this, I have managed to narrow down the images/xmls that create the issue. While doing that, another issue came out 

_panic: Couldn't decode ./Images/524flag.jpg_

I have added such images/xmls as well.

I have attached a zip containing the same setup as previous issues, I have also added a python script that converts the images, for convenience, since one is a PNG. Just run 

```
python convert.py
augoment -batch_size=1 -exclusion_threshold=1 -blur=2
```

Thank you for the assistance.
[bkp.zip](https://github.com/lootag/ImageAuGomentationCLI/files/5517982/bkp.zip)

**Comment by lootag** [comment]
Hey Guglielmo,
I'm glad you could find the issue. As for "panic: Couldn't decode ./Images/524flag.jpg", this is not a bug, it's a feature. It means the file got corrupted in some way (it's not encoded as an image) and so the decoder couldn't turn it into base64. Just remove the file in question (and its corresponding annotation) from the inputs, and everything should work out fine.
As always, try it out, then close the issue if it's solved.

I've done a major refactoring of the application in the past couple days (I've also added a Makefile which installs it automatically for the sake of simplicity). Now I'm adding some integration tests, and then I'm going to add proper logging. Hopefully that should make it easier to troubleshoot problems with the input.

At any rate, if you feel like some things are acting up, or that parts of the code could be written better, definitely branch away, edit, and then make a pull request: I'm almost surely going to accept it as long as it doesn't break any feature :-) 

You take care, and have a good night.

**Comment by guglielmogattiglio** [comment]
Thank you!
