### ISSUE TITLE
Size info with 0 values in xml

### ISSUE THREAD

**Issue by guglielmogattiglio** [lootag/ImageAuGomentationCLI#8]
flipped.xml
![image](https://user-images.githubusercontent.com/32592364/98488000-e752d880-2226-11eb-9fed-16d8960c332c.png)

rotate*.xml
![image](https://user-images.githubusercontent.com/32592364/98488009-f76ab800-2226-11eb-8dd7-f52d35de017c.png)

Note in the first case how size is all zero, while for the rotated one, depth only is zero. I have also attached a zip with reproducible example.
[temp.zip](https://github.com/lootag/ImageAuGomentationCLI/files/5507415/temp.zip)

Function call
`~/my_files/cv_proj/ImageAuGomentationCLI/ImageAuGomentationCLI -exclusion_threshold=1  -batch_size=1 -blur=20`

Thanks

**Comment by lootag** [comment]
This is also fixed Now! Try it out and close it if it works :-)
